replicaCount: 1

image: ghcr.io/inlets/inlets-pro:0.9.23
pullPolicy: IfNotPresent

tokenSecretName: inlets-pro-secret

autoTLS: false

# comma-separated list of TCP ports to forward
# i.e. for Istio/Nginx/Traefik:
# ports: 80,443
ports: 3000

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nameOverride: ""
fullnameOverride: ""
