replicaCount: 1

image:
  repository: ghcr.io/inlets/inlets-pro
  pullPolicy: IfNotPresent
  tag: "0.8.8"

tokenSecretName: inlets-pro-secret

autoTLS: false

ports: 3000

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nameOverride: ""
fullnameOverride: ""
