replicaCount: 1

image: ghcr.io/inlets/inlets-pro:0.9.23
pullPolicy: IfNotPresent

tokenSecretName: inlets-pro-secret

serviceType: ClusterIP
controlPlane:
  port: 8123

dataPlane:
  port: 8000

controlPlaneIngress:
  domain: tunnel1.example.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # cert-manager.io/issuer: "letsencrypt-prod"

dataPlaneIngresses:
  - domain: prometheus.example.com
    annotations:
      kubernetes.io/ingress.class: "nginx"
  #    cert-manager.io/issuer: "letsencrypt-prod"
  # - domain: openfaas.example.com
  #   annotations:
  #     kubernetes.io/ingress.class: "nginx"
  #     cert-manager.io/issuer: "letsencrypt-prod"

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

imagePullSecrets: []

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nameOverride: ""
fullnameOverride: ""
