apiVersion: v1
kind: Service
metadata:
  name: {{ include "inlets-pro.fullname" . }}-control
  labels:
    {{- include "inlets-pro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controlPlane.type }}
  ports:
  - port: {{ .Values.controlPlane.port }}
    name: control-plane
    protocol: TCP
    targetPort: {{ .Values.controlPlane.port }}
  selector:
    {{- include "inlets-pro.selectorLabels" . | nindent 4 }}
