{{- $fullName := include "inlets-http-server.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "inlets-http-server.labels" . | nindent 4 }}
  {{- with .Values.controlPlaneIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.controlPlaneIngress.domain }}
      secretName: {{ .Values.controlPlaneIngress.secretName }}
  rules:
    - host: {{ .Values.controlPlaneIngress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "inlets-http-server.fullname" . }}
                port:
                  number: {{ .Values.controlPlane.port }}
