{{- $top := . }}

{{- range $name, $data := .Values.dataPlaneIngresses }}
{{- $fullName := include "inlets-http-server.fullname" $top -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $name }}
  labels:
    {{- include "inlets-http-server.labels" $top | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ $data.domain }}
      secretName: {{ $data.secretName }}
  rules:
    - host: {{ $data.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "inlets-http-server.fullname" $top }}
                port:
                  number: {{ $top.Values.dataPlane.port }}
---
{{- end }}
