apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inlets-http-server.fullname" . }}
  labels:
    {{- include "inlets-http-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "inlets-http-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "inlets-http-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "inlets-http-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command:
           - inlets-pro
           - http
           - server
           - "--auto-tls=false"
           - "--token-from=/etc/inlets/token"
          ports:
            - name: control-plane
              containerPort: {{ .Values.controlPlane.port }}
              protocol: TCP
            - name: data-plane
              containerPort: {{ .Values.dataPlane.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: temp-volume
              mountPath: /tmp            
            - name: token
              mountPath: "/etc/inlets"
              readOnly: true
      volumes:
      - name: temp-volume
        emptyDir: {}         
      - name: token
        secret:
          secretName: {{ .Values.tokenSecretName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
