---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: inlets-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inlets-server
  template:
    metadata:
      labels:
        app: inlets-server
    spec:
      containers:
      - name: inlets-server
        image: inlets/inlets-pro:0.5.1
        imagePullPolicy: IfNotPresent
        command: ["inlets-pro"]
        args:
        - "inlets-server"
        - "--auto-tls=true"
        - "--remote-tcp 127.0.0.1"
        - "--common-name PUBLIC_IP_GOES_HERE"
        - "--token=AUTHTOKENHERE"
---
  